name: Integration test

on:
  push:
    branches:
      - main
  schedule:
    # Every month
    - cron:  '11 11 11 * *'

jobs:
  download-apply-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download Terraform state
        uses: devgioele/terraform-state-artifact@v3
        with:
          passphrase: ${{ secrets.TF_STATE_PASSPHRASE }}
          download-upload: download
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
      - name: Terraform init
        run: terraform init
      - name: Terraform validate
        run: terraform validate
      - name: Terraform apply
        run: terraform apply -auto-approve
      - name: Upload Terraform state
        uses: devgioele/terraform-state-artifact@v3
        with:
          passphrase: ${{ secrets.TF_STATE_PASSPHRASE }}
          download-upload: upload